### ISSUE TITLE
missing BDH project name on input parameter

### ISSUE THREAD

**Issue by sugu0620** [synopsys-sig/detect-action#59]
I would like to use my own custom project name and version during BDH scan. There is no input argument in the Action plugin. Please add or tell me a workaround for this issue.

**default behavior noticed tale repo name as BDH project name.

**Comment by RDarnel** [comment]
I would also like the ability to include the project name and possibly other custom args such as project version, excluded directories, search depth, etc.

**Comment by RDarnel** [comment]
In case anyone else is looking for this, I learned that there are some environment variable overrides built into the detect binary to help with this. Tracking down these environment variables have proven difficult, and I'm still struggling to track them down. Here's a couple that will help with the project name and version:

- DETECT_PROJECT_NAME
- DETECT_PROJECT_VERSION_NAME

Sample usage:
``` yaml

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "<Insert Build Step here>"
    - name: Run BD Detect
      uses: synopsys-sig/detect-action@v0.3.4
      env:
        DETECT_PROJECT_VERSION_NAME: "${{ env.VERSION }}"
        DETECT_PROJECT_NAME: "${{ github.repository }}"
      with:
        scan-mode: INTELLIGENT
        detect-version: 9.0.0
        ...
```
